### ISSUE TITLE
Bug: Presentations are uneditable on opentwincities.coeventer.com

### ISSUE THREAD

**Issue by wbushey** [campuscodefest/ccf#106]
Was just going through a demo of editing presentations at http://opentwincities.coeventer.com/events/20-presentation-demo , when I discovered that I can't actually edit a presentation. When I load a presentation, I see a `Error: _.contains is not a function`. Things work fine when trying this on localhost; maybe this is an asset compilation issue?

The linked to event is a dummy event running now until the 8th.

**Comment by pete2786** [comment]
Thanks, I noticed last week will get it figured out tonight.

**Comment by pete2786** [comment]
It was an issue with lodash versioning not being aligned with restangular... thankfully someone already posted about it on Github otherwise I'd be up all night! There was also a syntax change I had to accommodate for, it's working now.

Commit ref:
https://github.com/campuscodefest/ccf/commit/4cd200c53ef696b97c793a51458aefbe1db6b048 AND
https://github.com/campuscodefest/ccf/commit/fb5a26f8f3f9187896a8b4bdb7b7cf1f8de9e447

**Comment by wbushey** [comment]
:+1: Big, big thank you for fixing this so quickly. A lot of Geo:Coders are going to be happy this is working too.

:beers:

**Comment by pete2786** [comment]
No problem, IMO it's really one of the killer app features that make running a hackathon/hack day much easier. I was not happy seeing that something broke.
