### ISSUE TITLE
Enable the use of Meetup for Oauth

### ISSUE THREAD

**Issue by wbushey** [campuscodefest/ccf#74]
At @chadfennell's suggestion, I've been looking at CCF as a tool for [Open Twin Cities](http://opentwincities.org). I'm really liking the platform so far, and am seriously considering using it for an upcoming event. The one thing that would seriously prevent us from using CCF is the use of Google for authentication, as members of OTC are actually members of Meetup.

[Meetup does offer Oauth](http://www.meetup.com/meetup_api/auth/), and I'm thinking that implementing Meetup as an Oauth provider could be an OTC project. But before going to far, I wanted to ask if you see any problems with adding other Oauth provider, or what adding another provider might entail.

**Comment by pete2786** [comment]
Adding an OAuth provider would be small effort, as we already use OmniAuth. A lot of configuration and a little working on making sure the fields we pull match up.

**Comment by wbushey** [comment]
That's about what I was thinking @pete2786. 

One sticking point is that [Meetup does not provide email addresses through their API](https://groups.google.com/forum/#!topic/meetup-api/4ZttRt4NwnU). They instead offer an [API for sending messages to members](http://www.meetup.com/meetup_api/docs/2/message/), which I find awkward for a few reasons. Perhaps we could just ask users for their email address once they've authenticated...

Aside from email concerns, as far as I can tell, the work would be:

- Add Meetup as a provider in the [Omniauth initializer](https://github.com/campuscodefest/ccf/blob/master/config/initializers/omniauth.rb)
- Update [User.create_with_omniauth and User.find_and_update_uid](https://github.com/campuscodefest/ccf/blob/master/app/models/user.rb#L16) to use Meetup when appropriate (perhaps using [omniauth-meetup](https://github.com/tapster/omniauth-meetup) and/or [rmeetup](https://github.com/Jberlinsky/rmeetup) - though neither seem very active :( )
- A setting on the organization model indicating which OAuth provider to use
- Update [signin_path](https://github.com/campuscodefest/ccf/blob/master/app/helpers/application_helper.rb#L28) to use the appropriate path based on the org

**Comment by pete2786** [comment]
https://github.com/tapster/omniauth-meetup, this would probably be an excellent resource

**Comment by pete2786** [comment]
The email concern is a large-ish issue, since it's how we are currently identifying users. We could work around that by prompting for an email during the OAuth callback.

All other comments are spot on. I think we could provide configuration on which OAuth providers you'd like to make available to members, default to Google. We could also take this opportunity to add Facebook auth.

**Comment by pete2786** [comment]
I'm going to take a look at this tonight, figure out if we can remove email dependency. I'll dig in Meet up integration, but I'll have to see if I can get a free account to play around with.

**Comment by pete2786** [comment]
After scanning the code, I'd break out the following tasks:

* (As suggested) leverage the [https://github.com/tapster/omniauth-meetup](OmniAuth meetup gem)
* Create a OAuth provider configuration for those which do not provide an email address in the response. Add a two step process to enter an email AND validate the email. Once this is complete, user can be treated as normal, identified by uid on sign in. This add value beyond Meetup as I know off-hand Twitter does not like to provide email via their API either.
* I'd leave the option for all providers for all organizations. Users could belong to multiple organizations and use Google to provide their identity for others. Could add a preferred provider or something.
* This would be a good opportunity to follow a pattern I've used in the past, adding a Provider -> Users table, so you could an account associated with both Meetup, Google and maybe Facebook and other providers in the future. Otherwise, we could just be lazy and keep identities totally separate based upon "how" you sign in. It can get tricky because we'd need an attribute (like email) to verify, however I'd feel most comfortable with this approach.

**Comment by pete2786** [comment]
Started making progress on Provider User, should help make this transition slightly easier.

`validated` and `token` field will be leveraged by Meetup provider to ensure you cannot sign in fully with that account until you have provided an email and validated the email with the token provided.

https://github.com/campuscodefest/ccf/pull/75/files

**Comment by pete2786** [comment]
Implemented Facebook Auth as a secondary login option now. We should be able to follow this pattern for Meetup with out much effort (not worrying about the lack of an email being returned yet).

https://github.com/campuscodefest/ccf/pull/76/files

**Comment by wbushey** [comment]
Thank you @pete2786 for everything you've done so far. I agree with you that it's best to just ask users for their email address if using a provider that does not provide that information.

We have a meetup coming up on Tuesday in St. Paul. I plan on trying to get some work done on adding the Meetup provider then.

**Comment by wbushey** [comment]
Just tried signing in via meetup on coeventer.com. The first time I tried, I got a 500 on the oAuth callback. But when I tried again it worked just fine.

**Comment by pete2786** [comment]
I found the issue. I had been testing on the base URL (coeventer.com) there is an issue when you use a subdomain as it auto verifies you and then tries to send an email without a valid email address which causes a hard error.

**Comment by pete2786** [comment]
Fixed issue here: https://github.com/campuscodefest/ccf/commit/43defd913195c65ef1560643a1a170b5e01c560c

Thanks for reporting. Going to close this main issue and deal with one offs in separate issues for now! Thanks for all the work on this @wbushey
